Issue114
openzim/wikihow pull request #116
Opened 2022-02-18 09:55 UTC by fadiga

- build an expected_articles list/set using MW API, based on requested categories, --only and --exclude.
- Skip articles scraping for those not in the list
- Update rewriter to work off this new list instead of the current combination of options
- Update scrape_category_page to work with the new list
- remove cards instead of link target
- Update breadcrumb rewriting to work off the list

2022-02-21 11:31 UTC, rgaudin requested changes
Thanks ; see the many inline comments

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/utils.py
> +    return re.sub(r"^/", "", urllib.parse.urlparse(url).path)
Missing docstring, type hint and return type

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +from pywikiapi import Site
Not in requirements !!

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +        # set of all articles we've seen in related-articles links.
Why is this still present?

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
>          # idem, list of URLs which returned HTTP 404.
Idem will need to be rephrased

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
>      def single_category(self):
Missing docstring and return type

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/utils.py
> +def no_trailing_slash(text: str):
Missing return type

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/rewriter.py
> -        if (
this method is resource/time consuming so we definitely want to bypass it if we know it's not going to rewrite anything. I think the only remaining use case is when we requested the full run (no categories not `--only` nor `--excludes` set).

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/rewriter.py
>      def rewrite_links_for_excludes(self, soup, to_root):
Should be renamed to its new behavior: `remove_links_to_nonincluded_content()`

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/rewriter.py
> +                    if match and (
Should be `if match_path` now since it's already dependent on `match`.

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/rewriter.py
>                      if match and (
Should be if match_path now since it's already dependent on match.

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/rewriter.py
> +                        match_path in self.exclusion_categories
Why are we still testing over `exclusion_categories` ? I thought `exclusion_categories`'s role was just to feed `expected_categories`…

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/rewriter.py
> +                            self.inclusion_list
Same as above, why are we testing against `inclusion_list` ? and not just `expected_articles` ?

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +    def clean_category_title(self, title):
Better name: `cleaned_category_title()`. Also, add type hint, return type and docstring

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +        return (
Use a regexp: `re.sub(r"^" +self. metadata['category_prefix'] + r":", "", title)`

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +    def build_expected_categories(self):
Missing a docstring ; use it to briefly describe what it does

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +            # self.expected_categories = set()
remove commented code

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +                logger.info(f"category : {query}")
This is probably debug. Do we even need it?

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +                for q in site.query(
Don't use single letter variable names. Use `item` or `query` if nothing is more explicit

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +                        logger.info(f"subcat : {category_title}")
Same as above

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +        )
There we might want a debug log of all the expected categories (if it's not gonna change later)

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +        logger.info("Starting build categories to do")
`"Building list of expected categories"`

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +        logger.info("Starting build expected articles")
`"Building list of expected articles"`

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +            logger.info(f"Category : {category}")
Probably useless or debug

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +            f"Nb Category : {len(self.expected_categories)}"
`"Nb of expected categories: "`

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +            f"\nCategory exclusion {self.exclusion_categories}"
Why would this be relevant?

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +            f"NB expected articles : {len(self.expected_articles)}\n"
`"Nb of expected articles: "`

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +            f"Article inclusion {self.inclusion_list}\n"
Instead of those, we should have a debug log of the expected articles.

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
>                      if line.startswith("Category:"):
Following block would fail if line is `Category:`. Using a regexp would work: `if re.match(r"Category:.+", line):`

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +                f"{len(self.exclusion_categories)} categories excluded."
replace `categories excluded` by `categories to be excluded`

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +            logger.info(f"> {len(self.inclusion_list)} articles to include.")
`"... to be included"`

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +        logger.info("Starting scraping from articles")
`"Scraping expected articles"`

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +        for e, article in enumerate(self.expected_articles, 1):
Use `index` instead of `e`.

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +            logger.info(f"{e}/{len(self.expected_articles)}")
This is more likely a DEBUG than an INFO

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
>          logger.info("Starting scraping from categories")
`"Scraping expected category pages"`

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +            breadcrumbs=get_footer_crumbs_from(soup, self.exclusion_categories),
I believe the list is in the Global now so it shouldn't be passed to the function. Also, I believe the function should use `expected_categories` instead. right?

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
>          self.articles.add(article)
Do we still need this? It's not only used to display stats at the end of the scrape. We already have a list of expected articles and missing articles. Only difference is the footer links… that are also in a list

2022-02-21 11:31 UTC, rgaudin commented on wikihow2zim/scraper.py
> +            breadcrumbs=get_footer_crumbs_from(soup, self.exclusion_categories),
Same comment as for category_page

2022-02-22 13:01 UTC, rgaudin commented on wikihow2zim/scraper.py
>      def single_category(self):
Still missing Return type

2022-02-22 13:13 UTC, rgaudin commented on wikihow2zim/utils.py
> +    return re.sub(r"^/", "", urllib.parse.urlparse(url).path)
Missing docstring

2022-02-22 13:26 UTC, rgaudin commented on wikihow2zim/scraper.py
>          # idem, list of URLs which returned HTTP 404.
`Idem` string is not applicable anymore

2022-02-22 13:27 UTC, rgaudin commented on wikihow2zim/scraper.py
>      def single_category(self):
Missing return type

2022-02-24 11:18 UTC, rgaudin requested changes
Thank you, the code is fine but the --exclude is not working as expected.

When launching on `Python/`, with an exclude file containing `Use-Windows-Command-Prompt-to-Run-a-Python-File`, I see that it was registered.

```
Articles exclusion : {'Use-Windows-Command-Prompt-to-Run-a-Python-File'}
```

And actually, the link to it is removed from the Category page (in the blocks, the intro contains a link to it but that's not something we want to handle at this point) but… the article is included in the ZIM…

```
[MainThread::2022-02-24 12:13:58,054] INFO:-> article : Use-Windows-Command-Prompt-to-Run-a-Python-File
```

So it seems to be in inclusion list but also in expected list…

2022-02-24 20:54 UTC, rgaudin requested changes
Good! Now please check, fix and mark resolve all the inline comments once OK.

2022-02-25 11:29 UTC, fadiga commented on wikihow2zim/scraper.py
> +                logger.info(f"category : {query}")
It is deleted

2022-02-28 13:08 UTC, rgaudin approved these changes
Good!

2022-02-28 13:08 UTC, merged