Added docker file and set up github actions with docker
openzim/wikihow pull request #12
Opened 2021-08-05 18:15 UTC by ElenaKusevska

2021-08-05 18:39 UTC, rgaudin requested changes
Looks good ; please take a look at my inline comments.

2021-08-05 18:39 UTC, rgaudin commented on Dockerfile
> +LABEL org.opencontainers.image.source https://github.com/openzim/kolibri2zim
repo name is `kolibri`

2021-08-05 18:39 UTC, rgaudin commented on .github/workflows/docker.yml
> +      - feature_docker
Change to master. We'll ensure it's working fine once merged

2021-08-05 18:39 UTC, rgaudin commented on Dockerfile
> +
Please add locale and timezone

```Dockerfile
RUN echo "UTC" >  /etc/timezone
ENV TZ "UTC"

# setup locale
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
```
```

2021-08-05 18:39 UTC, rgaudin commented on Dockerfile
> +RUN wget -L http://tmp.kiwix.org/wheels/libzim-1.0.0.dev1-cp38-cp38-manylinux1_x86_64.whl http://tmp.kiwix.org/wheels/zimscraperlib-1.4.0.dev1-py3-none-any.whl
Just do as for sotoki

```Dockerfile
# TEMP: install pylibzim and scraperlib through built wheels (until release)
RUN wget --progress=dot:giga http://tmp.kiwix.org/wheels/libzim-1.0.0.dev1-cp38-cp38-manylinux1_x86_64.whl \
    && wget --progress=dot:giga http://tmp.kiwix.org/wheels/zimscraperlib-1.4.0.dev2-py3-none-any.whl \
    && pip install --no-cache-dir ./*.whl && rm -f ./*.whl
```

2021-08-05 18:39 UTC, rgaudin commented on Dockerfile
> +RUN cd /src/ && python3 ./setup.py install
/src can be removed after install. /output can be created at that moment as well

2021-08-05 23:49 UTC, ElenaKusevska commented
@rgaudin Please review the PR again, and let me know if it's OK, or I should make some more changes.

2021-08-06 09:15 UTC, rgaudin commented
Thank you @ElenaKusevska ; that's good. Can you please rewrite the git history? Then we'll merge.

Also, please remove the `WORKDIR /output`, doesn't make much sense.

2021-08-06 09:15 UTC, rgaudin approved these changes

2021-08-06 14:03 UTC, ElenaKusevska commented
@rgaudin check if it's OK now.

2021-08-06 14:16 UTC, rgaudin commented
That will do. thanks

2021-08-06 14:17 UTC, merged